/** The review report (full evidence, written to a project file) and the few lines printed for the agent. */
import type { Measure } from "./measures.ts";

const pct = (m: Measure): string => (m.rate === null ? "n/a" : `${Math.round(m.rate * 100)}%`);
const UNIT_WORD: Record<Measure["id"], string> = { cross_section_refs: "objects", macro_redundancy: "sentences", citation_isolation: "citing sentences", evidence_gap: "result tables" };
const MAX_UNITS = 40;

export function renderReport(entry: string, date: string, measures: Measure[]): string {
  const rows = measures.map((m) => `| ${m.name} | ${pct(m)} | ${m.flagged} of ${m.total} ${UNIT_WORD[m.id]} | ${m.weak ? `weak: ${m.weak}` : m.rate === null ? "not applicable" : ""} |`);
  const sections = measures.map((m) => {
    const head = [`## ${m.name}`, "", m.note ?? "", ""];
    if (m.weak) head.push(`**Weak evidence:** ${m.weak}.`, "");
    if (m.units.length === 0) return [...head, m.rate === null ? "Not applicable to this manuscript." : "Nothing flagged.", ""].join("\n");
    const shown = m.units.slice(0, MAX_UNITS).map((u) => `- \`${u.where.file}:${u.where.line}\` [${u.section}] ${u.excerpt}`);
    if (m.units.length > MAX_UNITS) shown.push(`- … and ${m.units.length - MAX_UNITS} more`);
    return [...head, ...shown, ""].join("\n");
  });
  return [
    `# Manuscript review: ${entry}`,
    "",
    `Generated by \`uktub-scholar review\` on ${date}. Deterministic: no model, no network, nothing leaves this machine.`,
    "",
    "> Four structural diagnostics from Oh et al., \"Science or Slop?\" (arXiv 2610.00531), reimplemented from the paper's Appendix A. Each is the share of",
    "> units flagged (higher is worse). On the authors' benchmark they separate AI-written from human-written papers pairwise; a high share is a",
    "> reason to look at the listed places, not a verdict that the manuscript is poor or machine-written. Fix the reasoning, not the count.",
    "",
    "## Summary",
    "",
    "| Measure | Share flagged | Units | Note |",
    "|---|---|---|---|",
    ...rows,
    "",
    ...sections,
  ].join("\n");
}

export function summaryLines(entry: string, reportRel: string, measures: Measure[]): string[] {
  return [
    `Review of ${entry}: full report with file:line evidence written to ${reportRel}`,
    ...measures.map((m) => `  ${m.name.toLowerCase().padEnd(24)} ${pct(m).padStart(4)}  (${m.flagged} of ${m.total} ${UNIT_WORD[m.id]})${m.weak ? ` [weak: ${m.weak}]` : m.rate === null ? " [not applicable]" : ""}`),
    "These are diagnostics from deterministic checks, not a verdict; read the report for what to look at.",
  ];
}
